namespace: codebolab
name: devops
version: 0.1.0
readme: README.md
homepage: https://github.com/codebolab/infraestructure
repository: https://github.com/codebolab/infraestructure
authors:
  - Jose Maria Zambrana Arze
build_ignore:
  - sensitive
  - .DS_Store
  - .git
  - .gitignore
  - '*.pyc'
  - '*.swp'
  - '*.tar.gz'
  - playbooks/vars/credentials.yml
  - playbooks/vars/platform.yml
  - private
  - untracked
