# Call with:
#
#   $ ansible-playbook --ask-vault-pass playbooks/turndown_elasticache.yml
#
- hosts: localhost
  vars:
    env_name: development
  vars_files:
    - "vars/credentials.yml"
    - "vars/platform.yml"
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  tasks:
    - name: Account information
      aws_caller_info:
      register: caller_info

    - set_fact:
        account_id: "{{ caller_info['account'] }}"

    # Turning down Elasticache
    # -------------------------------------
    - name: Removes cache cluster
      elasticache:
        name: "{{ platform_name }}"
        state: absent

    - name: Removes a subnet group
      elasticache_subnet_group:
        state: absent
        name: "{{ platform_name }}-cache"

    - name: Delete group limited-ec
      ec2_group:
        name: "limited-ec"
        vpc_id: "{{ vpc_id }}"
        state: absent
