galaxy_info:
  role_name: initializer_base
  author: Jose Maria Zambrana Arze
  description: Initialize a AWS CentOS Linux server with python development tools
  license: MIT
  min_ansible_version: 3.0
  galaxy_tags:
    - AWS
    - Centos
