- name: Copy nginx config file
  copy:
    content: "{{ lookup('template', 'proxy.conf') }}"
    dest: "/etc/nginx/sites-enabled/{{ service_name }}.conf"

- service:
    name: nginx
    state: reloaded
