galaxy_info:
  role_name: initializer_docker
  author: Jose Maria Zambrana Arze
  description: Install and configure docker service for AWS CentOS Linux server
  license: MIT
  min_ansible_version: 3.0
  galaxy_tags:
    - AWS
    - Centos
    - Docker
