galaxy_info:
  role_name: cluster_facts
  author: Jose Maria Zambrana Arze
  description: Retrieve information about cluster, subnets and security groups
  license: MIT
  min_ansible_version: 3.0
  galaxy_tags:
    - AWS
