galaxy_info:
  role_name: cluster_gateways
  author: Jose Maria Zambrana Arze
  description: Creates internet gateway and, if set, a NAT gateway
  license: MIT
  min_ansible_version: 3.0
  galaxy_tags:
    - AWS
