- ec2_eip_info:
    filters:
      tag:Name: "{{ platform_name }}-head"
  register: head_eip

- debug:
    var: head_eip

- name: allocate eip for head
  ec2_eip:
    region: "{{ aws_region }}"
    in_vpc: yes
    reuse_existing_ip_allowed: yes
    tag_name: "Name"
    tag_value: "{{ platform_name }}-head"
  register: eip_created
  when: head_eip['addresses']|length == 0

- debug:
    var: eip_created

- ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ eip_created['allocation_id'] }}"
    state: present
    tags:
      Name: "{{ platform_name }}-head"
  when: eip_created.skipped is not defined

- ec2_eip_info:
    filters:
      tag:Name: "{{ platform_name }}-head"
  register: head_eip

- set_fact:
    head_ip: "{{ head_eip.addresses[0].public_ip }}"

- name: Create a ec2 instance 
  include_role:
    name: cluster_ec2
  vars:
    public_ip: "{{ head_ip }}"

- set_fact:
    head_internal_ip: "{{ ec2_ips[platform_name + '-head'] }}"
