- hosts: localhost
  vars_files:
    - "vars/credentials.yml"
    - "vars/platform.yml"
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  tasks:
    - name: Account information
      aws_caller_info:
      register: caller_info

    - set_fact:
        account_id: "{{ caller_info['account'] }}"

    - set_fact:
        domain_name: "{{ platform_name }}search"

    - name: Deploy elasticsearch server in AWS
      include_role:
        name: codebolab.devops.elasticsearch
