- name: Create directory for private
  file:
    path: "{{ playbook_dir | dirname }}/private"
    state: directory

- name: Create an EC2 key
  ec2_key:
    name: "{{ platform_name }}"
    region: "{{ aws_region }}"
  notify:
    - Save private key
